eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka

server.port=8080

spring.application.name=api-gateway

#logging.level.root=INFO
#logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator = INFO
#logging.level.org.springframework.cloud.gateway = TRACE

# Currency Service Route
spring.cloud.gateway.server.webflux.routes[0].id=currency-service
#spring.cloud.gateway.server.webflux.routes[0].uri=http://currency-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://currency-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0].=Path=/api/currency

# Transaction Service Route
spring.cloud.gateway.server.webflux.routes[1].id=transaction-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://transaction-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0].=Path=/api/transaction

# Wallet Service Route
spring.cloud.gateway.server.webflux.routes[2].id=wallet-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://wallet-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0].=Path=/api/wallet

# Discovery Server Route
spring.cloud.gateway.server.webflux.routes[3].id=discovery-server
spring.cloud.gateway.server.webflux.routes[3].uri=http://discovery-server:8761
spring.cloud.gateway.server.webflux.routes[3].predicates[0].=Path=/eureka/web
spring.cloud.gateway.server.webflux.routes[3].filters[0]=SetPath=/

# Discovery Server Static Resources Route
spring.cloud.gateway.server.webflux.routes[4].id=discovery-server-static
spring.cloud.gateway.server.webflux.routes[4].uri=http://discovery-server:8761
spring.cloud.gateway.server.webflux.routes[4].predicates[0].=Path=/eureka/**