eureka.instance.hostname=localhost
# it is a server so we dont want to register it as client
eureka.client.register-with-eureka=false
# we dont need to fetch registry, because it is already here
eureka.client.fetch-registry=false

# whenever client want to register to discovery server, server sends its local copy
# of registry of clients
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
server.port=8761

spring.application.name=discovery-server